export * as Rec from "./Record"
export * as Arr from "./Array"
export { NonEmptyArray } from "./Array/types"
export * as Either from "./Either"
export * as Equal from "./Order/Equal"
export * as Ord from "./Order/Orderable"
export * as Sg from "./Semigroup"

export { Applicative } from "./typeclass/applicative"
export { Apply } from "./typeclass/apply"
export { Foldable } from "./typeclass/foldable"
export { Functor } from "./typeclass/functor"
export { Monad } from "./typeclass/monad"
export { Monoid } from "./typeclass/monoid"
export { Semigroup } from "./typeclass/semigroup"
export { Traversable } from "./typeclass/traversable"
